- Meadowlark-js/backends/meadowlark-mongodb-backend/src/repository/Upsert.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/Upsert.ts
- Meadowlark-js/tests/system/crud/Delete.test.ts
- Meadowlark-js/tests/system/crud/SystemTestSetup.ts
We were not adding the descriptor references to the outRefs of the document in both PostgreSQL and MongoDB
Also added system test covering this issue
> RND-296 - Descriptors could be deleted when another document was referencing descriptor

- Meadowlark-js/backends/meadowlark-mongodb-backend/src/model/MeadowlarkDocument.ts
- Meadowlark-js/backends/meadowlark-mongodb-backend/src/repository/Db.ts
- Meadowlark-js/backends/meadowlark-mongodb-backend/src/repository/Delete.ts
- Meadowlark-js/backends/meadowlark-mongodb-backend/src/repository/ReferenceValidation.ts
- Meadowlark-js/backends/meadowlark-mongodb-backend/src/repository/Update.ts
- Meadowlark-js/backends/meadowlark-mongodb-backend/src/repository/Upsert.ts
- Meadowlark-js/backends/meadowlark-mongodb-backend/test/integration/Update.test.ts
- Meadowlark-js/backends/meadowlark-mongodb-backend/test/integration/Upsert.test.ts
- Meadowlark-js/backends/meadowlark-mongodb-backend/test/integration/locking/Delete.test.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/Db.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/Delete.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/Get.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/OwnershipSecurity.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/ReferenceValidation.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/SqlHelper.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/SystemTestHelper.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/Update.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/Upsert.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/Delete.test.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/Read.test.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/TestHelper.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/Update.test.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/Upsert.test.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/locking/Delete.test.ts
This 1st commit is for PostgreSQL. Aside from directly renaming "existence" to "alias", changes are around related function naming for clarity/action-orientation, and enhancement of comments. Also a `let` -> `const` in there, but no logic changes.
> [RND-346] change existence table related naming to alias

- .editorconfig
- .github/workflows/codeql.yml
- .github/workflows/dependencies.yml
- .github/workflows/reports.yml
- .github/workflows/test.yml
This allows PR's from forks to be able to run the testing without getting errors generating reports.
* Moving report generation to a different workflow to avoid failures from community contributions
* Setting up working directory for test workflow
* Adding reports workflow to create test reports of execution
* Using matrix to generate reports
> [RND-360] Creating workflow for report generation

- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/Delete.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/Get.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/OwnershipSecurity.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/ReferenceValidation.ts
These are all checks to make sure that the objects returned from a query have a rows object before access. I don't see a problem with these in general, but... 
If a database or table gets deleted while Meadowlark running the query will error, and wind up in the catch block which will end with a 500 error to the client, it will never hit the rows objects.
If a table is deleted and Meadowlark is restarted, there is no error, any query that attempts to hit a non-existent table will return empty and thus most of the time act like a 404.
If the database gets deleted and Meadowlark is restarted, the database is generated.
> [RND-299] - Harden PostgreSQL error handling

- .github/workflows/reports.yml
- .github/workflows/test.yml
- Meadowlark-js/tests/e2e/setup/e2e.env
- eng/setup-mongo.sh
- Adding end to end tests running Fastify and Postgres Backend
- Separating testing process into two jobs
- Adding MongoDB Action to run Mongo Tests
- Including new files to reporter.
Must be approved after https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-Actions/pull/32 is merged.
> [RND-365] Run End To End Tests

- .github/workflows/test.yml
- Make linting the first step.
- This step also builds and cache the node_modules.
- The cache for node_modules is calculated with the yarn.lock file so it will be using the cache until the dependencies change.
- All other tests run after the linting and use the cache for the dependencies.
- Use env variables for postgres user and password to avoid defining it in multiple places.
> [RND-461] Refactor test action

- .github/workflows/after-pullrequest.yml
- .github/workflows/on-pullrequest.yml
- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/SystemTestHelper.ts
- Meadowlark-js/tests/system/crud/SystemTestSetup.ts
- Create build step as previous step to e2e to have packages ready for execution.
- Convert unit, integration and system tests into a matrix since behavior is similar for all.
- Save MongoDB in cache to run tests.
- Fix error when running system tests isolated given that it was depending on integration tests setup
> [RND-461] CI Performance Improvements

- Meadowlark-js/packages/meadowlark-core/src/handler/DescriptorLoader.ts
- Meadowlark-js/packages/meadowlark-core/src/handler/FrontendRequest.ts
- Meadowlark-js/packages/meadowlark-core/test/extraction/DocumentInfoExtractor.test.ts
- Meadowlark-js/packages/meadowlark-core/test/handler/FrontendRequest.test.ts
- Meadowlark-js/packages/meadowlark-core/test/plugin/NoDocumentStorePlugin.test.ts
- Meadowlark-js/packages/meadowlark-core/test/plugin/NoQueryHandlerPlugin.test.ts
- Add tests cases for Plugin\NoQueryHandlerPlugin and Plugin\NoDocumentStorePlugin
- Add comment to ignore DescriptorLoader.ts
- Update handler\FrontendRequest.ts. to export removeReferencesDocumentIdentity.
- Add unit test for Handler\FrontendRequest.ts.test
- Add unit test for extraction\DocumentInfoExtractor.ts.test
> [RND-386] Increase test coverage for meadowlark-core folder

- docs/LOCALHOST.md
Remove the "or higher" mention on the NodeJS version to only support v16
> [RND-475] Update documentation to only support NodeJS v16

- Meadowlark-js/package-lock.json
- Meadowlark-js/packages/meadowlark-utilities/src/Logger.ts
Update timestampFormat (Logger.ts) to use 'YYYY-MM-DD HH:mm:ss' instead of 'YYYY-MM-DD HH:mm:SS'
Update date format for the logger to include seconds and milliseconds.
```2023-01-31 15:53:46.025 debug not-applicable Spawning 12 worker threads 
2023-01-31 15:53:46.028 debug not-applicable Primary process ID 31364 is running 
2023-01-31 15:53:46.266 debug not-applicable Worker 25852 is listening 
2023-01-31 15:53:46.268 debug not-applicable Worker 10796 is listening 
2023-01-31 15:53:46.268 debug not-applicable Worker 24204 is listening 
2023-01-31 15:53:46.269 debug not-applicable Worker 38320 is listening 
2023-01-31 15:53:46.269 debug not-applicable Worker 31316 is listening 
2023-01-31 15:53:46.270 debug not-applicable Worker 37296 is listening 
```
- [ x ] Bug fix (non-breaking change …
> [RND-459] Invalid DateTime String in Winston Configuration

- Meadowlark-js/backends/meadowlark-mongodb-backend/docker/scripts/mongo-rs-setup.sh
In order to have mongo2 and mongo3 working as secondary nodes, we need to change the priority value to something greater than 0. 
This is part of what the documentation says about the priority value:
```
A number that indicates the relative eligibility of a member to become a primary.
Specify higher values to make a member more eligible to become primary, and lower values to make the member less eligible. A member with a members[n].priority of 0 is ineligible to become primary.
```
Based on this, if the primary node (mongo1) fails, we currently don’t have a node to replace it as the primary one.
The arbiter is not actually required. Based on the documentation:
`In some circumstances (such as when you have a primary and a secondary, but cost constraints prohibit adding another secondary), …
> [RND-267] Changes priority values on the docker mongo replica set configuration.

- Meadowlark-js/backends/meadowlark-mongodb-backend/src/repository/Db.ts
- Meadowlark-js/backends/meadowlark-mongodb-backend/src/repository/ReferenceValidation.ts
Check reference difference using AliasIds instead of _id. 
Update findReferencedDocumentIdsById:
- Replace MeadowlarkDocumentId by MeadowlarkDocument.
- Add AliasIds to find projection
> [RND-491] Update documents reference validation.

- Meadowlark-js/backends/meadowlark-mongodb-backend/src/BackendFacade.ts
- Meadowlark-js/backends/meadowlark-mongodb-backend/src/index.ts
- Meadowlark-js/backends/meadowlark-mongodb-backend/src/repository/Db.ts
- Meadowlark-js/backends/meadowlark-opensearch-backend/src/BackendFacade.ts
- Meadowlark-js/backends/meadowlark-opensearch-backend/src/index.ts
- Meadowlark-js/backends/meadowlark-opensearch-backend/src/repository/Db.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/src/BackendFacade.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/src/index.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/Db.ts
- Meadowlark-js/packages/meadowlark-core/src/handler/Connection.ts
- Meadowlark-js/packages/meadowlark-core/src/handler/FrontendFacade.ts
- Meadowlark-js/packages/meadowlark-core/src/index.ts
- Meadowlark-js/packages/meadowlark-core/src/plugin/backend/DocumentStorePlugin.ts
- Meadowlark-js/packages/meadowlark-core/src/plugin/backend/NoDocumentStorePlugin.ts
- Meadowlark-js/packages/meadowlark-core/src/plugin/backend/NoQueryHandlerPlugin.ts
- Meadowlark-js/packages/meadowlark-core/src/plugin/backend/QueryHandlerPlugin.ts
- Meadowlark-js/services/meadowlark-fastify/src/Service.ts
- Meadowlark-js/services/meadowlark-fastify/src/ServiceFactory.ts
- Meadowlark-js/services/meadowlark-fastify/src/handler/CrudHandler.ts
- Meadowlark-js/services/meadowlark-fastify/src/handler/MeadowlarkConnection.ts
Add functions to close backend connections when the service is closed.
- Add closeConnection to every backend db.ts.
- Update interfaces to include the closeConnection function.
- Invoke closeConnection to API onClose.
Ex. MongoDb.
Number of connections:
> [RND-481] Close all database connections when API exits

- Meadowlark-js/packages/meadowlark-utilities/src/Logger.ts
Entering a wrong connection string on mongo prints the user and password
- Add function to remove sensitive data from logged message. Update Logger call.
- Result:
```
Error connecting MongoDb URL: "mongodb://*****:*****@mongo1:27017,mongo2:27018,mongo3:27019/?replicaSet=rs0". Error was Authentication failed.
```
> [RND-509] A wrong connection string on mongo prints the user and password

- Meadowlark-js/jest.config.js
- Meadowlark-js/tests/config/e2e/jest.config.js
- Meadowlark-js/tests/config/integration/jest.config.js
- Meadowlark-js/tests/config/jest.config.js
- Meadowlark-js/tests/config/unit/jest.config.js
- Fix the scope of jest.config.js to properly separate global and project parameters.
- Fix parameter redundancy.
> [RND-505] Terminal throws some warnings when I try to run individual test files with npx

- Meadowlark-js/backends/meadowlark-opensearch-backend/package.json
- Meadowlark-js/package-lock.json
- Meadowlark-js/package.json
- Meadowlark-js/tests/e2e/helpers/Credentials.ts
- Meadowlark-js/tests/e2e/package.json
- Meadowlark-js/tests/e2e/readme.md
- Meadowlark-js/tests/e2e/setup/.env.example
- Meadowlark-js/tests/e2e/setup/DevModeConfig.ts
- Meadowlark-js/tests/e2e/setup/EnvironmentConfig.ts
- Meadowlark-js/tests/e2e/setup/Setup.ts
- Meadowlark-js/tests/e2e/setup/Teardown.ts
- Meadowlark-js/tests/e2e/setup/containers/ApiContainer.ts
- Meadowlark-js/tests/e2e/setup/containers/MongoContainer.ts
- Meadowlark-js/tests/e2e/setup/containers/OpenSearchContainer.ts
- docs/LOCALHOST.md
Adding a developer mode for e2e tests to speed up the test creation/debugging process
TestContainers has a 'ryuk' container that runs as the handler of the container lifecycle.
Disabling this container and adding an option to reuse containers allows us to set up the container once and then use it for the tests.
To use we need to set the DEVELOPER_MODE flag and after running it once, save the Admin Key and Secret.
> [RND-512] e2e Developer Mode

- .github/workflows/on-pullrequest.yml
- Meadowlark-js/backends/meadowlark-mongodb-backend/test/integration/Config.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/package.json
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/config/integration/jest.config.js
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/Connection.test.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/Delete.test.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/OwnershipSecurity.test.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/Read.test.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/SecurityMiddleware.test.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/Update.test.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/Upsert.test.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/locking/Delete.test.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/setup/Config.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/setup/Global.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/setup/PostgresqlContainer.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/setup/Setup.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/setup/Teardown.ts
- Meadowlark-js/package-lock.json
Running integration tests for Postgres required a local environment already set in order to run the tests in local.
- Setting up test containers for Postgres on integration tests
- Using current setup on GH Actions since running Postgres in Ubuntu can be done with built in service.
- Introducing a global beforeAll to do the setup and avoid requiring this before each test. (This should be used only in cases when the function is truly global, to avoid unexpected behavior on tests since it can be obscure),
> [RND-467] Run Integration Tests for Postgres with TestContainers

- Meadowlark-js/backends/meadowlark-mongodb-backend/src/model/MeadowlarkDocument.ts
- Meadowlark-js/backends/meadowlark-mongodb-backend/src/repository/Db.ts
- Meadowlark-js/backends/meadowlark-mongodb-backend/src/repository/Get.ts
- Meadowlark-js/backends/meadowlark-mongodb-backend/src/repository/Update.ts
- Meadowlark-js/backends/meadowlark-mongodb-backend/src/repository/Upsert.ts
- Meadowlark-js/backends/meadowlark-mongodb-backend/test/integration/Read.test.ts
- Meadowlark-js/backends/meadowlark-mongodb-backend/test/integration/locking/Delete.test.ts
- Meadowlark-js/backends/meadowlark-mongodb-backend/test/model/MeadowlarkDocument.test.ts
- Meadowlark-js/backends/meadowlark-mongodb-backend/test/repository/Update.test.ts
- Add CreatedAt and LastModifiedDate as UNIX Timestamps
```
{
"_id": "2_wmVcaVb7e8wDIWYsCSBJd4pR62uXOIM0F-fw",
...
"createdBy": "meadowlark_verify-only_key_1",
"createdAt": 1683304825911,
"lastModifiedAt": 1683304850567
}
```
- Add _lastModifiedDate to mongoDb response.
```
{
"id": "57cade80-76eb-45be-bdcd-478d2065adf1",
"classroomIdentificationCode": "string",
"schoolReference": {
"schoolId": 255901107
},
"maximumNumberOfSeats": 28,
"optimalNumberOfSeats": 11,
"_lastModifiedDate": "2023-05-05T16:40:50.567Z"
}
```
- Update mongoDb tests.
> [RND-522] Add CreatedAt and LastModifiedDate to Meadowlark - MongoDB

- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/Delete.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/SqlHelper.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/Update.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/Delete.test.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/Update.test.ts
Update delete and update modules.
Update test to validate if aliases and references are deleted when a document is deleted. Update update module to use an old meadowlarkId to filter aliases and references, because, if it change, this query will return empty. Add validation to use enable or disable allow Identity Updates
> [RND-560] Postgres: Deleting resource is not deleting references and alias

- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/OwnershipSecurity.ts
- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/Upsert.ts
- Meadowlark-js/tests/e2e/scenarios/SecurityValidation.test.ts
Update ownership validation, to validate first by documentUuid, if that id is null, it tries to find the document by meadowlarkId.
> [RND-556] Fix faulty ownership security on POST requests

- Meadowlark-js/backends/meadowlark-opensearch-backend/test/setup/OpenSearchContainer.ts
- Meadowlark-js/tests/e2e/setup/containers/OpenSearchContainer.ts
A previous [PR](https://github.com/Ed-Fi-Exchange-OSS/Meadowlark/pull/250) updated the OpenSearch version for the Dockerfiles, and we missed to update the version on the test setup. This PR updates the versions to run the tests for OpenSearch
> [RND-565] Update open search image version for test execution

- eng/deploy/azure/.env.example
- eng/deploy/azure/README.md
- eng/deploy/azure/azure-docker-compose.yml
- Update documentation and instructions to deploy Meadowlark with the Azure CLI.
- Include reorganization and warning about Docker Compose integration since it's still available but will be discontinued.
Introduced the use of variables to simplify the setup and shorten the instructions.
- Add details about the need of using a unique URL name per Azure subscription.
> [RND-581] Deploy Meadowlark with Azure CLI

- Meadowlark-js/tests/e2e/scenarios/ResourcesCRUDValidation.test.ts
Adding a test that verifies the current behavior. This will fail once the changes are implemented and the ID is required
> Adding test to replicate scenario where ID is included in PUT

- Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/Db.ts
Add validation to show a message if POSTGRES_USER and POSTGRES_PASSWORD parameters are missing in the .env file.
> RND-548 Improve error handling for PostgreSQL missing credentials

- .github/workflows/on-prerelease.yml
Use sha256sum instead of iconv to generate hash, iconv is getting errors parsing out to ASCII from UTF-16. sha256sum is the method used in Admin API to generate the hash.
> [RND-659] On pre release action: Fix SBOM hash generation

- Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/locking/Delete.test.ts
- docs/performance-testing/postgres-SSI-performance-testing.md
- Add documentation about PostgreSQL Serializable Snapshot Isolation (SSI) performance testing 
- Add a note to locking\delete.test.ts
> [RND-643] Serializable Snapshot Isolation (SSI) in PostgreSQL

- .github/workflows/on-pullrequest.yml
- Meadowlark-js/backends/meadowlark-elasticsearch-backend/package.json
- Meadowlark-js/backends/meadowlark-mongodb-backend/package.json
- Meadowlark-js/backends/meadowlark-opensearch-backend/package.json
- Meadowlark-js/backends/meadowlark-postgresql-backend/docker/docker-compose.yml
- Meadowlark-js/backends/meadowlark-postgresql-backend/package.json
- Meadowlark-js/lerna.json
- Meadowlark-js/package-lock.json
- Meadowlark-js/packages/meadowlark-authz-server/package.json
- Meadowlark-js/packages/meadowlark-core/package.json
- Meadowlark-js/packages/meadowlark-utilities/package.json
- Meadowlark-js/services/meadowlark-fastify/package.json
- Meadowlark-js/tests/e2e/package.json
- Meadowlark-js/tests/e2e/readme.md
- Meadowlark-js/tests/e2e/setup/.env-e2e.example
- Meadowlark-js/tests/e2e/setup/SetupTestContainers.ts
- Setting up mongo in e2e tests only when required.
- Update e2e tests documentation.
- Refactor versioning logic to run tests in main without adding multiple ifs in the code.
> [RND-653] Refactor Config file to not require mongodb URI

- Meadowlark-js/backends/meadowlark-elasticsearch-backend/package.json
- Meadowlark-js/backends/meadowlark-mongodb-backend/package.json
- Meadowlark-js/backends/meadowlark-opensearch-backend/package.json
- Meadowlark-js/backends/meadowlark-postgresql-backend/package.json
- Meadowlark-js/lerna.json
- Meadowlark-js/package-lock.json
- Meadowlark-js/package.json
- Meadowlark-js/packages/meadowlark-authz-server/package.json
- Meadowlark-js/packages/meadowlark-authz-server/src/handler/CreateClient.ts
- Meadowlark-js/packages/meadowlark-authz-server/src/handler/RequestToken.ts
- Meadowlark-js/packages/meadowlark-authz-server/src/handler/UpdateClient.ts
- Meadowlark-js/packages/meadowlark-authz-server/src/handler/VerifyToken.ts
- Meadowlark-js/packages/meadowlark-authz-server/src/validation/BodyValidation.ts
- Meadowlark-js/packages/meadowlark-authz-server/test/validation/BodyValidation.test.ts
- Meadowlark-js/packages/meadowlark-core/package.json
- Meadowlark-js/packages/meadowlark-utilities/package.json
- Meadowlark-js/services/meadowlark-fastify/package.json
- Meadowlark-js/tests/e2e/package.json
- Meadowlark-js/tests/e2e/scenarios/AuthenticationValidation.test.ts
- Meadowlark-js/tests/e2e/scenarios/AuthorizationValidation.test.ts
- Meadowlark-js/tests/http/local.RND663.http
Allow case insensitivity in OAuth requests, by checking suggestions given to properties, and applying those suggestions if valid.
The ODS/API allows for the payload of the requests to be case insensitive, which means that clientname, clientName and CLIENTNAME should all be valid in the payload.
In order to do that, we need to update the payload from the request with a suggested value.
- Update logging in changed classes to use helper function and match the other methods (trying to unify process on those similar classes)
> [RND-663] Allow case insensitivity in OAuth requests

- Meadowlark-js/backends/meadowlark-elasticsearch-backend/package.json
- Meadowlark-js/backends/meadowlark-mongodb-backend/package.json
- Meadowlark-js/backends/meadowlark-opensearch-backend/package.json
- Meadowlark-js/backends/meadowlark-postgresql-backend/package.json
- Meadowlark-js/lerna.json
- Meadowlark-js/package-lock.json
- Meadowlark-js/packages/meadowlark-authz-server/package.json
- Meadowlark-js/packages/meadowlark-core/package.json
- Meadowlark-js/packages/meadowlark-utilities/package.json
- Meadowlark-js/services/meadowlark-fastify/package.json
- Meadowlark-js/tests/e2e/helpers/Resources.ts
- Meadowlark-js/tests/e2e/package.json
- Meadowlark-js/tests/e2e/scenarios/ResourcesCRUDValidation.test.ts
Current behavior depends on a previous test before doing the next one, for example, to test the delete, it requires a previous it() to have run to set the element to delete, this causes a race condition since we cannot guarantee that the prerequisite will run first. This move that behavior as part of the before all hook
> [RND-697] Refactor test to avoid race conditions on depending tests

- Meadowlark-js/.env.example
- Meadowlark-js/backends/meadowlark-elasticsearch-backend/package.json
- Meadowlark-js/backends/meadowlark-mongodb-backend/package.json
- Meadowlark-js/backends/meadowlark-opensearch-backend/package.json
- Meadowlark-js/backends/meadowlark-postgresql-backend/package.json
- Meadowlark-js/lerna.json
- Meadowlark-js/package-lock.json
- Meadowlark-js/packages/meadowlark-authz-server/package.json
- Meadowlark-js/packages/meadowlark-core/package.json
- Meadowlark-js/packages/meadowlark-utilities/package.json
- Meadowlark-js/services/meadowlark-fastify/package.json
- Meadowlark-js/tests/e2e/package.json
- Meadowlark-js/tests/e2e/readme.md
- k8s/README.md
- k8s/app-configmap.yaml
- k8s/app-secret.yaml
- k8s/meadowlark-api-deployment.yaml
- k8s/meadowlark-api-service.yaml
- k8s/opensearch-deployment.yaml
- k8s/opensearch-persistentvolumeclaim.yaml
- k8s/opensearch-service.yaml
- k8s/postgres-deployment.yaml
- k8s/postgres-persistentvolumeclaim.yaml
- k8s/postgres-service.yaml
Add a set of configuration files to run Meadowlark in a Kubernetes cluster
- Migrate from docker compose using komposer.
- Create ConfigMap to handle parameters, and Secret file to handle passwords
- Add instructions to deploy locally.
> [RND-676] Kubernetes Configuration for Meadowlark
