Meadowlark-js/backends/meadowlark-mongodb-backend/src/repository/Update.ts, Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/Update.ts, Meadowlark-js/tests/system/crud/Delete.test.ts
The original PR for RND-296 included only fixes for upsert, this adds the fixes for update as well
=> Missed update fixes

docs/LOCALHOST.md
Missed when removing code in first PR
=> Removing AWS-Lambda related setup documentation

Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/Update.ts, Meadowlark-js/tests/http/local.33b.http, Meadowlark-js/tests/http/local.33b.superclass.http, Meadowlark-js/tests/http/local.common.collection.issue.http, Meadowlark-js/tests/http/local.deleteissue.http, Meadowlark-js/tests/http/local.ownership-tests.http, Meadowlark-js/tests/http/local.token.http, Meadowlark-js/tests/http/manual.system.test.http
Also added an existence check to update, so that an error response is returned when you try to insert on an update
=> RND-345 - Remove hard coded tokens from http test files

.github/workflows/test.yml
Setting retention-days for uploaded artifacts
=> [RND-362] Set retention-days for uploaded artifacts

Meadowlark-js/packages/meadowlark-core/src/extraction/DocumentReferenceExtractor.ts, Meadowlark-js/packages/meadowlark-core/test/extraction/DocumentReferenceExtractor.test.ts
also updated version of test reporter
=> [RND-426] - Unable to create StudentSchoolAssociation with GraduationPlan reference

Meadowlark-js/packages/meadowlark-core/src/handler/FrontendRequest.ts, Meadowlark-js/packages/meadowlark-core/src/metaed/MetaEdValidation.ts, Meadowlark-js/packages/meadowlark-core/src/middleware/ValidateQueryMiddleware.ts, Meadowlark-js/packages/meadowlark-core/test/metaed/MetaEdValidation.test.ts
Fix query parameters not validating for non string values
Also fixed related unit tests that were being skipped Added unit tests for query parameter validation
=> [RND-427] - Unable to query school by schoolId

.github/workflows/on-pullrequest.yml, Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/SystemTestHelper.ts, Meadowlark-js/tests/system/crud/SystemTestSetup.ts
- Fix issue with system tests setup
=> [RND-461] Split test execution to make build faster

.github/workflows/on-pullrequest.yml
After updating the dependencies, some were left out
=> [RND-462] Fixing action versions with difference within same yml file

Meadowlark-js/packages/meadowlark-utilities/src/Environment.ts, Meadowlark-js/services/meadowlark-fastify/src/Cluster.ts, Meadowlark-js/services/meadowlark-fastify/src/Factory.ts, Meadowlark-js/services/meadowlark-fastify/src/index.ts, Meadowlark-js/tests/e2e/management/Setup.ts, NOTICES.md
When running the bulk load for main, these were the results in my computer:
Execution for branch:
Local execution:
=> [RND-464] Create clusters for fastify

Meadowlark-js/services/meadowlark-fastify/src/Cluster.ts, Meadowlark-js/services/meadowlark-fastify/src/Factory.ts, Meadowlark-js/services/meadowlark-fastify/src/handler/DescriptorLoader.ts, Meadowlark-js/services/meadowlark-fastify/src/handler/MeadowlarkConverter.ts, Meadowlark-js/services/meadowlark-fastify/src/handler/MetadataHandler.ts, Meadowlark-js/services/meadowlark-fastify/src/index.ts
Add comment to ignore these files:
- Cluster.ts
- Factory.ts
- Index.ts
- handler/DescriptorLoader.ts
- handler/MetadataHandler.ts
- handler/MeadowlarkConverter.ts
=> [BIA-387] Increase test coverage for meadowlark-fastify folder

.github/workflows/on-pullrequest-dockerfile.yml, Meadowlark-js/Dockerfile
Fix dockerfile GitHub Action
- Fix action that was not running.
- Adjust dockerfile based on lint recommendations.
=> Fix Dockerfile GitHub Action

.vscode/extensions.json, docs/design/README.md, docs/design/offline-cascading-deletes/README.md
Note the new recommended extension in VS Code.
=> [RND-493] Implementation design for offline cascading deletes

Meadowlark-js/services/meadowlark-fastify/readme.md, docs/CONFIGURATION.md, docs/LOCALHOST.md, docs/README.md
Update documentation to fix links and add additional information.
=> [RND-526] Doc updates for those new to Meadowlark

docs/design/README.md, docs/design/performance-benchmarking/README.md, docs/design/read-performance-benchmarking/README.md, eng/performance/GetAll-Performance.ps1
Adding details to run performance tests for Meadowlark
=> [RND-533] Technical design for get all performance benchmarking

docker/Dockerfile
- Add antlr4 url from azure artifacts instead of myget. 
- Move ARG line.
- Add ML_VERSION to npm install
=> [RND-579] Update docker/Dockerfile

eng/bulkLoad/Invoke-LoadPartialGrandBend.ps1, eng/bulkLoad/Invoke-LoadSouthridge.ps1, eng/bulkLoad/modules/BulkLoad.psm1, eng/bulkLoad/modules/Package-Management.psm1, eng/performance/BulkLoad-Performance.ps1
- Create script to download zipped file.
- Insert data into Meadowlark.
- Measure performance
Verified that this creates the missing data reported in the original ticket
=> [RND-585] Adding script to write Southridge data into Meadowlark

Meadowlark-js/backends/meadowlark-elasticsearch-backend/src/repository/QueryElasticsearch.ts
=> [RND-597] On ElasticSearch logs, prints the actual query, instead of Object.

Meadowlark-js/tests/e2e/scenarios/MultipleReferenceValidation.test.ts
=> RND-612 Review skipped e2e tests

Meadowlark-js/backends/meadowlark-kafka-stream/docker/docker-compose.yml, Meadowlark-js/package-lock.json, Meadowlark-js/package.json, Meadowlark-js/tests/config/unit/jest.config.js, Meadowlark-js/tests/kafka/kafkajs-worker/kafkajsWorker.ts, Meadowlark-js/tests/kafka/kafkajsWorker.test.ts, Meadowlark-js/tests/kafka/rdkafka-worker/rdkafkaWorker.text, Meadowlark-js/tests/kafka/rdkafka-worker/rdkafkaWorker.ts, eng/Run-DevContainers.ps1
- Recreate Kafka container to enable listener.
- Add sample code to read topics from Kafka using Kafkajs and rdkafka.
- Clients use read each message and read from batch
- Add parameter groupId to set the group name.
- When a message is written to the kafka topic, the consume reads it and prints it to the console.
- If you run the client with different GroupId, each client will read everything from the message group. If they share groupId, the message read by one will not be available to the other.
**Kafkajs** 
- Run test  npx jest .\tests\kafka\kafkajsWorker.test.ts
- Read from batch: eachBatch handler will feed your function batches and provide some utility functions to give your code more flexibility: resolveOffset, heartbeat, commitOffsetsIfNecessary, uncommittedOffsets, isRunning, …
=> RND-558 Reading from Kafka Topics

docker/kafka/ed-fi-kafka-connect-transforms/README.md, docker/kafka/ed-fi-kafka-connect-transforms/src/main/java/com/github/edfiexchangeoss/meadowlark/kafka/connect/transforms/GenerateIndexFromResource.java, docker/kafka/ed-fi-kafka-connect-transforms/src/test/java/com/github/edfiexchangeoss/meadowlark/kafka/connect/transforms/GenerateIndexFromResourceTest.java, eng/Run-DevContainers.ps1
- Update GenerateIndexFromResource to update index and replace dots.
- Remove validation to append descriptor part to index name.
- Update tests
=> [RND-629] Fix issues with kafka sink to opensearch transformation

Meadowlark-js/backends/meadowlark-elasticsearch-backend/test/QueryElasticsearch.test.ts, Meadowlark-js/backends/meadowlark-opensearch-backend/src/repository/OpenSearchException.ts, Meadowlark-js/backends/meadowlark-opensearch-backend/src/repository/QueryOpensearch.ts, Meadowlark-js/backends/meadowlark-opensearch-backend/test/QueryOpensearch.test.ts, Meadowlark-js/tests/e2e/scenarios/QueryStringValidation.test.ts
=> [RND-521] - Changes from the current SQL style query to DSL query on Opensearch.

Meadowlark-js/backends/meadowlark-mongodb-backend/src/repository/ReferenceValidation.ts, Meadowlark-js/tests/e2e/scenarios/ResourcesReferenceValidation.test.ts, Meadowlark-js/tests/http/RND-637.http
=> [RND-637] - Unable to POST a new School

README.md, docs/DATA-AUTHORIZATION.md
Add data authorization documentation from Techdocs
=> [RND-572] Add the documentation on Meadowlark's authorization

Meadowlark-js/backends/meadowlark-elasticsearch-backend/src/repository/ElasticSearchException.ts, Meadowlark-js/backends/meadowlark-elasticsearch-backend/test/integration/QueryElasticsearch.test.ts, Meadowlark-js/backends/meadowlark-opensearch-backend/src/repository/OpenSearchException.ts, Meadowlark-js/backends/meadowlark-opensearch-backend/test/integration/QueryOpensearch.test.ts, Meadowlark-js/packages/meadowlark-core/src/handler/Query.ts, Meadowlark-js/packages/meadowlark-core/src/message/QueryResult.ts
=> [RND-641] Adds QUERY_FAILURE_INDEX_NOT_FOUND as a QueryResult response

Meadowlark-js/backends/meadowlark-elasticsearch-backend/src/repository/ElasticSearchException.ts, Meadowlark-js/backends/meadowlark-elasticsearch-backend/test/QueryElasticsearch.test.ts, Meadowlark-js/backends/meadowlark-opensearch-backend/src/repository/OpenSearchException.ts, Meadowlark-js/backends/meadowlark-opensearch-backend/test/QueryOpensearch.test.ts, Meadowlark-js/packages/meadowlark-core/src/handler/Query.ts, Meadowlark-js/packages/meadowlark-core/src/message/QueryResult.ts, Meadowlark-js/packages/meadowlark-core/test/handler/Query.test.ts
=> [RND-642] Adds QUERY_FAILURE_CONNECTION_ERROR as a QueryResult response

.github/workflows/on-pullrequest.yml, CONTRIBUTORS.md, Meadowlark-js/backends/meadowlark-postgresql-backend/package.json, Meadowlark-js/backends/meadowlark-postgresql-backend/src/BackendFacade.ts, Meadowlark-js/backends/meadowlark-postgresql-backend/src/index.ts, Meadowlark-js/backends/meadowlark-postgresql-backend/src/model/AuthorizationDocument.ts, Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/Db.ts, Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/SqlHelper.ts, Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/authorization/CreateAuthorizationClient.ts, Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/authorization/GetAllAuthorizationClients.ts, Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/authorization/GetAuthorizationClient.ts, Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/authorization/ResetAuthorizationClientSecret.ts, Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/authorization/TryCreateBootstrapAuthorizationAdmin.ts, Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/authorization/UpdateAuthorizationClient.ts, Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/TestHelper.ts, Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/authorization/CreateAuthorizationClient.test.ts, Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/authorization/GetAllAuthorizationClients.test.ts, Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/authorization/GetAuthorizationClient.test.ts, Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/authorization/ResetAuthorizationClientSecret.test.ts, Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/authorization/TryCreateBootstrapAuthorizationAdmin.test.ts, Meadowlark-js/backends/meadowlark-postgresql-backend/test/integration/authorization/UpdateAuthorizationClient.test.ts, Meadowlark-js/package-lock.json, Meadowlark-js/tests/e2e/setup/containers/ApiContainer.ts
Move and update [DenverPublicSchools](https://github.com/DenverPublicSchools/Meadowlark/tree/main) code.
- Update functions to move sql scripts to SqlHelper. 
- Add tests
=> [RND-422] Client Management API: authentication and token management with PostgreSQL

docs/performance-testing/postgres-performance-testing.md
Add documentation about performances test.  We use two methods
- Test connections and database pooling, we use Autocannon tool to get metrics.
- Test impact of indexes and database changes, we use postgres statistics to generate metrics and compare
=> [RND-647] Postgres performance testing

.github/workflows/on-merge-to-main.yml, .github/workflows/on-prerelease.yml, .github/workflows/on-pullrequest-dockerfile.yml, .github/workflows/on-pullrequest.yml, .github/workflows/on-release.yml, Meadowlark-js/backends/meadowlark-elasticsearch-backend/package.json, Meadowlark-js/backends/meadowlark-mongodb-backend/package.json, Meadowlark-js/backends/meadowlark-opensearch-backend/package.json, Meadowlark-js/backends/meadowlark-postgresql-backend/package.json, Meadowlark-js/lerna.json, Meadowlark-js/package-lock.json, Meadowlark-js/packages/meadowlark-authz-server/package.json, Meadowlark-js/packages/meadowlark-core/package.json, Meadowlark-js/packages/meadowlark-utilities/package.json, Meadowlark-js/services/meadowlark-fastify/package.json, Meadowlark-js/tests/e2e/package.json
Update versions of GitHub actions used
=> [RND-657] Update GitHub Actions versions

Meadowlark-js/backends/meadowlark-elasticsearch-backend/package.json, Meadowlark-js/backends/meadowlark-mongodb-backend/package.json, Meadowlark-js/backends/meadowlark-opensearch-backend/package.json, Meadowlark-js/backends/meadowlark-postgresql-backend/package.json, Meadowlark-js/lerna.json, Meadowlark-js/package-lock.json, Meadowlark-js/packages/meadowlark-authz-server/package.json, Meadowlark-js/packages/meadowlark-core/package.json, Meadowlark-js/packages/meadowlark-utilities/package.json, Meadowlark-js/services/meadowlark-fastify/package.json, Meadowlark-js/services/meadowlark-fastify/src/Service.ts, Meadowlark-js/services/meadowlark-fastify/test/Get.test.ts, Meadowlark-js/tests/e2e/package.json, Meadowlark-js/tests/e2e/scenarios/AuthenticationValidation.test.ts, Meadowlark-js/tests/e2e/scenarios/AuthorizationValidation.test.ts
=> [RND-663] Allow case insensitivity in OAuth requests

Meadowlark-js/backends/meadowlark-elasticsearch-backend/package.json, Meadowlark-js/backends/meadowlark-mongodb-backend/package.json, Meadowlark-js/backends/meadowlark-opensearch-backend/package.json, Meadowlark-js/backends/meadowlark-postgresql-backend/package.json, Meadowlark-js/lerna.json, Meadowlark-js/package-lock.json, Meadowlark-js/package.json, Meadowlark-js/packages/meadowlark-authz-server/package.json, Meadowlark-js/packages/meadowlark-core/package.json, Meadowlark-js/packages/meadowlark-utilities/package.json, Meadowlark-js/sample-load-balancer.conf, Meadowlark-js/services/meadowlark-fastify/package.json, Meadowlark-js/tests/e2e/package.json, docs/design/rate-limiting-for-oauth/README.md
Setup and documentation for doing rate limiting with nginx setup
=> [RND-665] Lower rate limiting for OAuth

.github/workflows/on-pullrequest.yml, Meadowlark-js/.vscode/settings.json, Meadowlark-js/backends/meadowlark-elasticsearch-backend/package.json, Meadowlark-js/backends/meadowlark-mongodb-backend/package.json, Meadowlark-js/backends/meadowlark-opensearch-backend/package.json, Meadowlark-js/backends/meadowlark-postgresql-backend/package.json, Meadowlark-js/lerna.json, Meadowlark-js/package-lock.json, Meadowlark-js/packages/meadowlark-authz-server/package.json, Meadowlark-js/packages/meadowlark-core/package.json, Meadowlark-js/packages/meadowlark-utilities/package.json, Meadowlark-js/services/meadowlark-fastify/package.json, Meadowlark-js/tests/e2e/package.json, eng/deploy/azure/README.md
Instructions to use Azure Key Vault to handle credentials for Meadowlark deployment
=> [RND-675] Adding instructions to use Azure Key Vault
